version: '3.3'

services:
  user-service:
    build: ./
    command: ./user-service #add ./wait-for-postgres.sh db
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=admin

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/date
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
    - 5436:5432